# Алгоритми за пребарување

# Претставување граф преку речник

In [2]:
class Graph():
    
    def __init__(self):
        self.dict = {} 
    
    def add_node(self, node):
        self.dict[node] = []
        
    def add_edge(self, edge, add_reversed=True):
        node1, node2 = edge
        self.dict[node1].append(node2)
        if add_reversed:
            self.dict[node2].append(node1)
        
    def give_nodes(self):
        return list(self.dict)
    
    def give_edges(self):
        edges = []
        for vertex in self.graph_dict: #vertex=node
            for neighbour in self.graph_dict[vertex]:
                edges.append((vertex, neighbour))
        return edges
    
    def give_neighbors(self, node):
        return self.dict[node]

    #najchesto ovie nadole ne se koristat
    def remove_vertex(self, vertex_to_remove):
        del self.dict[vertex_to_remove] 
        for vertex in self.vertices():
            if vertex_to_remove in self.dict[vertex]:
                self.dict[vertex].remove(vertex_to_remove)

    def remove_edge(self, edge_to_remove, remove_reversed=True):
        vertex1, vertex2 = edge_to_remove
        if vertex2 in self.dict[vertex1]:
            self.dict[vertex1].remove(vertex2)
        if remove_reversed:
            if vertex1 in self.dict[vertex2]:
                self.dict[vertex2].remove(vertex1)

    def isolated_vertices(self):
        #jazol koj ne e povraan so nikoj ima prazna lista
        isolated_vertices = []
        for vertex in self.dict:
            if not self.dict[vertex]:
                isolated_vertices.append(vertex)
        return isolated_vertices

# Пребарување по широчина BFS
кога на излез ја сакаме цела постапка, а крајната состојба веќе знаеме што треба да биде
пр. движење коњ во најмалце чекори, движење плочки сложувалка во најмалце чекори, преминување мост/река

In [3]:
from queue import deque

In [4]:
def breadth_first_search_find_path(graph, starting_vertex, goal_vertex):
    if starting_vertex == goal_vertex:
        return []
    visited = {starting_vertex} 
    queue = deque([[starting_vertex]]) 
    while queue:
        vertex_list = queue.popleft() 
        vertex_to_expand = vertex_list[-1]
        for neighbour in graph.neighbours(vertex_to_expand): #mesto graph. treba da stoi expand_state
            if neighbour not in visited:
                if neighbour == goal_vertex:
                    return vertex_list + [neighbour]
                visited.add(neighbour)
                queue.append(vertex_list + [neighbour])

# Пребарување по длабочина DFS
кога на излез не сакаме постапка, туку крајна состојба
пр. еден начин за поставување кралици, судоку

In [6]:
def depth_first_search_find_path(graph, starting_vertex, goal_vertex):
    if starting_vertex == goal_vertex:
        return []
    visited = {starting_vertex}
    queue = deque([[starting_vertex]])
    while queue:
        vertex_list = queue.popleft()
        vertex_to_expand = vertex_list[-1]
        for neighbour in graph.neighbours(vertex_to_expand): #mesto graph..... expand_state
            if neighbour not in visited:
                if neighbour == goal_vertex:
                    return vertex_list + [neighbour]
                visited.add(neighbour)
                queue.appendleft(vertex_list + [neighbour])

# Претставување тежински граф

In [ ]:
class WeightedGraph:
    def __init__(self):
        self.graph_dict = {}
    
    def add_vertex(self, vertex):
        if vertex not in self.graph_dict:
            self.graph_dict[vertex] = {}
    
    def vertices(self):
        return list(self.graph_dict.keys())
    
    def add_edge(self, edge, add_reversed=True):
        vertex1, vertex2, weight = edge
        self.graph_dict[vertex1][vertex2] = weight
        if add_reversed:
            self.graph_dict[vertex2][vertex1] = weight
    
    def edges(self):
        edges = []
        for vertex in self.graph_dict:
            for neighbour, weight in self.graph_dict[vertex].items():
                edges.append((vertex, neighbour, weight))
        return edges
    
    def neighbours(self, vertex):
        return list(self.graph_dict[vertex].items())

# Пребарување со униформна цена

In [ ]:
import heapq

In [1]:
def uniform_cost_search(graph,starting_vertex, goal_vertex):
    if starting_vertex == goal_vertex:
        return []
    expanded = set()
    queue = [(0, [starting_vertex])]
    heapq.heapify(queue)
    while queue:
        weight, vertex_list = heapq.heappop(queue) 
        vertex_to_expand = vertex_list[-1]
        if vertex_to_expand == goal_vertex:
            return weight, vertex_list
        if vertex_to_expand not in expanded:
            for new_weight, neighbour in expand_state(vertex_to_expand):
                if neighbour not in expanded: 
                    heapq.heappush(queue, (weight + new_weight, vertex_list + [neighbour]))
        expanded.add(vertex_to_expand)

# Пребарувања два во едно

In [2]:
from queue import deque

In [ ]:
def search(initial_state, alg):
    visited = {initial_state}
    queue = deque([[initial_state]])
    c = 0
    while queue:
        c += 1
        vertex_list = queue.popleft()
        state_to_expand = vertex_list[-1]
        for next_state in expand_state(state_to_expand):
            if next_state not in visited:
                if check_end(next_state):
                    return vertex_list + [next_state], c
                visited.add(next_state)
                if alg == 'dfs':
                    queue.appendleft(vertex_list + [next_state])
                elif alg == 'bfs':
                    queue.append(vertex_list + [next_state])

# A* пребарување со евристика

In [7]:
import heapq

In [11]:
def a_star_search(graph, starting_vertex, goal_vertex, heuristic_function, alpha=1):
    if starting_vertex == goal_vertex:
        return []
    expanded = set()
    queue = [((0, 0), [starting_vertex])]
    heapq.heapify(queue)
    while queue:
        weight_tuple, vertex_list = heapq.heappop(queue)
        current_a_star_weight, current_path_weight = weight_tuple
        vertex_to_expand = vertex_list[-1]
        if vertex_to_expand == goal_vertex:
            return current_path_weight, vertex_list
        if vertex_to_expand not in expanded:
            for neighbour, new_weight in graph.neighbours(vertex_to_expand):
                if neighbour not in expanded:
                    heuristic = heuristic_function(neighbour, goal_vertex)
                    path_weight = current_path_weight + new_weight
                    a_star_weight = path_weight + alpha * heuristic
                    heapq.heappush(queue, ((a_star_weight, path_weight), vertex_list + [neighbour]))
        expanded.add(vertex_to_expand)

In [1]:
# evristika d_heuristic = {'S': 12, 'A': 5, 'B': 5, 'C': 5, 'D': 2, 'E': 2, 'F': 1, 'G': 1, 'H': 0} 
def heuristic(vertex, goal_vertex):
    return d_heuristic[vertex]

In [2]:
#za plochki, kako matrica
def heuristics(state):
    value = 0
    for index_row, row in enumerate(state):
        for index_col, col in enumerate(row):
            value += manhattan_distance((index_row, index_col), col)
    return value

In [ ]:
N=broj
def h(state):
    m = []
    for i, s in enumerate(state):
        s = int(s)
        m.append(manhattan_distance((i // N, i % N), (s // N, s % N)))
    return sum(m)

### Менхетен
* растојание ако одиме само хоризонтално или вертикално
* d = | x1 - x2 | + | y1 - y2 |

In [12]:
def manhattan_distance(state_1, state_2):
    return abs(state_1[0] - state_2[0]) + abs(state_1[1] - state_2[1])

### Чебишев
* растојание според вертикални, хоризонтални и дијагонални правци
* d = max( | x1 - x2 |, | y1 - y2 | )

In [14]:
def chebyshev_distance(state_1, state_2):
    return max(abs(state_1[0] - state_2[0]), abs(state_1[1] - state_2[1]))

### Евклид
* реалното растојание
* d = sqrt( ( x1 - x2 )^2 + ( y1 - y2 )^2 )

In [15]:
import math

def eucledian_distance(state_1, state_2):
    return math.sqrt((state_1[0] - state_2[0])**2 + (state_1[1] - state_2[1])**2)

# Минимакс

In [1]:
def minimax(graph, node, player):
    if node in leafs:
        print(node, end=' ')
        return leafs[node]
    best = plus_inf if player == 'MIN' else minus_inf
    for child in graph.neighbours(node): #ili expand_state
        result = minimax(graph, child, other_player(player))
        if player == 'MIN' and result < best:
            best = result
        elif player == 'MAX' and result > best:
            best = result
    return best

# Минимакс со алфа-бета поткастрување

In [2]:
plus_inf = float('inf')
minus_inf = float('-inf')

In [3]:
def minimax_alpha_beta(graph, node, player, alpha=minus_inf, beta=plus_inf):
    if node in leafs:
        print(node, end=' ')
        return leafs[node]
    best = plus_inf if player == 'MIN' else minus_inf
    for child in graph.neighbours(node):
        result = minimax_alpha_beta(graph, child, other_player(player), alpha, beta)
        if player == 'MIN':
            if result <= alpha:
                return result
            if result < beta:
                beta = result
            if result < best:
                best = result
        elif player == 'MAX':
            if result >= beta:
                return result
            if result > alpha:
                alpha = result
            if result > best:
                best = result
    return best

In [ ]:
#minimax so dlabochina
def minimax_alpha_beta(state, player,alpha=minus_inf, beta=plus_inf, depth=0):
    if check_score(state,player)!= 'keep_playing':
        return scores[check_score(state)],None 
    # пример како да се прекине со пребарување после длабочина 3
    if depth == 3:
        return evaluate_state(state),None  #evaluate_state ustvari e procenkata koj e pobednik
    best = plus_inf if player == 'MIN' else minus_inf
    best_move = None
    symbol='x' if player=='MAX' else 'o'
    for next_state, next_move in expand_state(state, player):
        result, result_move = minimax(next_state, turn(player),alpha,beta,depth+1)
        if player == 'MIN':
            if result <= alpha:
                return result, best_move
            if result < beta:
                beta = result
            if result < best:
                best = result
                best_move = move
        elif player == 'MAX':
            if result >= beta:
                return result, best_move
            if result > alpha:
                alpha = result
            if result > best:
                best = result
                best_move = result_move
    return best, best_move

# Невронски мрежи

In [2]:
import numpy as np
from plotly import graph_objects as go

In [1]:
class NeuralNetwork:
    def __init__(self):
        self.weights = 2 * np.random.random((3, 1)) - 1
                                          # (3, 1) => 3 редици, 1 колона
        
    @staticmethod
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))
    
    @staticmethod
    def sigmoid_derivative(x):
        return x * (1 - x)
                       #x                    #y                  
    def train(self, training_set_inputs, training_set_outputs, alpha=1, number_of_training_iterations=100): #aplha mozhe da e bilo koj broj, najubavo pogolem ama ne premn
        for iteration in range(number_of_training_iterations):
            output = self.predict(training_set_inputs) # [y1, y2, y3]
            #y'=self.predict(x) go trenirame y taka shto go prakjame x
            #error=y-y'
            error = training_set_outputs - output # [y1realno -y1, y2realno - y2, y3realno - y3]
                # error е матрица - разлика меѓу вистинскиот излези и predicted излези
            adjustment = np.dot(training_set_inputs.T, error * self.sigmoid_derivative(output))
                # ова го земаме с=здраво за готово
                # np.dot <=> множење на матрици
            self.weights += alpha * adjustment
            
    def predict(self, inputs):
        return self.sigmoid(np.dot(inputs, self.weights)) # [y1, y2, y3]
            # prediction e матрица 3х1 каде секој член е y = f1*w1 + f2*w2 + f3*w3

In [4]:
# Intialise a single neuron neural network. inicijalizacija na nevronska mrezha i nejzinite tezhini
neural_network = NeuralNetwork()
neural_network.weights

array([[ 0.83103026],
       [-0.42454339],
       [-0.46127862]])

In [5]:
# The training set. We have 4 examples, each consisting of 3 input values
# and 1 output value.
training_set_inputs = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
])
training_set_outputs = np.array([[0, 1, 1, 0]]).T #transponirana znaci .T

In [8]:
# Train the neural network using a training set.
# Do it 10,000 times and make small adjustments each time.
neural_network.train(training_set_inputs, training_set_outputs, alpha=0.01, number_of_training_iterations=10000)

In [7]:
neural_network.weights #novite tezhini po treniranje na mrezhata

array([[ 0.83103026],
       [-0.42454339],
       [-0.46127862]])

In [8]:
# Test the neural network with a new situation.
new_input = np.array([1, 0, 0])
y=neural_network.predict(new_input)
y

array([0.69657273])

In [9]:
actual_new_neural_network = int(np.round(y))
actual_new_neural_network #za da zaokruzhi na 0 ili 1 ako izlezot e 0 ili 1 shto se bara

1